name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test - ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: feud-app/yarn.lock

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './feud-app/src-tauri -> target'

      - name: Install frontend dependencies
        run: |
          cd feud-app
          yarn install

      - name: Run frontend checks
        run: |
          cd feud-app
          yarn build

      - name: Run Rust checks
        run: |
          cd feud-app/src-tauri
          cargo check --all-features
          cargo test --all-features
          cargo clippy -- -D warnings

      - name: Build Tauri app
        run: |
          cd feud-app
          yarn tauri build --debug