name: Release Tauri App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: feud-app/yarn.lock

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './feud-app/src-tauri -> target'

      - name: Install frontend dependencies
        run: |
          cd feud-app
          yarn install

      - name: Set version
        id: version
        run: |
          chmod +x scripts/auto-version.sh
          VERSION=$(./scripts/auto-version.sh --quiet)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          ./scripts/auto-version.sh

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ steps.version.outputs.VERSION }}
          releaseName: 'Chantskis Feud v${{ steps.version.outputs.VERSION }}'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
          projectPath: feud-app
          args: ${{ matrix.args }}

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get version
        id: version
        run: |
          chmod +x scripts/auto-version.sh
          VERSION=$(./scripts/auto-version.sh --quiet)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: v${{ steps.version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}